apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dna-volume
  namespace: brevitas
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 24Gi
